config/routes.rb
Rails.application.routes.draw do
  #resources :represents
  resources :departments
  resources :courses
  resources :tutorials
  resources :tags
  resources :services#, except: :create #per evitare che mi risponda create al posto di find_near_services con metodo POST
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :user_sessions, only: [:create, :destroy]
  resources :users, only: [:index, :new, :create]
  resources :pages, only: [:index]
  #root to: 'tags#index'
  get '/', to: 'tags#index'
  get 'tags', to: 'tags#index'
  get 'tutorials', to:'tutorials#index'
  get 'services', to:'services#index'
  get 'result', to: 'tags#index'
  post 'result', to: 'courses#result'
  post 'servicesa.json', to: 'services#find_near_services'
  get 'departments.json', to: 'departments#index'
  delete 'sign_out', to: 'user_sessions#destroy', as: :sign_out
  get 'sign_in', to: 'user_sessions#new', as: :sign_in
end

app/models/service.rb
class Service < ApplicationRecord
    has_many :connects
    has_many :tags, through: :connects

    def self.find_services_by_department_lat_lng(latitude, longitude)
        if(latitude[0] == '-')
            lat = latitude[0..5]
        else
            lat = latitude[0..4]
        end
        if(longitude[0] == '-')
            lng = longitude[0..5]
        else
            lng = longitude[0..4]
        end
        lat = lat + '%'
        lng = lng + '%'
        services1 = Service.where("latitude LIKE ? AND longitude LIKE ?", lat, lng)
        services = services1
        n_serv = services1.count
        if(n_serv <= 2)
            new_lng = longitude.to_f
            new_lng += 0.01
            new_lng = new_lng.to_s
            if(new_lng[0] == '-')
                n_lng = new_lng[0..5]
            else
                n_lng = new_lng[0..4]
            end
            n_lng = n_lng + '%'
            services2 = Service.where("latitude LIKE ? AND longitude LIKE ?", lat, n_lng)
            services = services1 | services2
            n_serv = services2.count
            #da deccomentare qual'ora si sia in un'altro meridiano
            # if(n_serv <= 2)
            #     new_lat = latitude.to_f
            #     new_lat += 0.01
            #     new_lat = new_lat.to_s
            #     if(new_lat[0] == '-')
            #         n_lat = new_lat[0..5]
            #     else
            #         n_lat = new_lat[0..4]
            #     end
            #     n_lat = n_lat + '%'
            #     services3 = Service.where("latitude LIKE ? AND longitude LIKE ?", n_lat, lng)
            #     services = services1 | services2 | services3
            # end
        end
        return services
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
    respond_to do |format|
      format.html
      format.json { render json: @services }
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #POST /services.json
  def find_near_services
    @services = Service.find_services_by_department_lat_lng(params[:latitude], params[:longitude])
    respond_to do |format|
      format.html
      format.json { render json: @services }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :office, :site, :latitude, :longitude)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <div class="text-center">
            <h3><i class="fas fa-pencil-alt"></i> <%= @service.name %></h3>
          </div>
        </div>

        <div class="card-body text-white bg-dark scroll scroll-x">
          <div class="form-group">
            <div class="field">
              <%= form.label :name %>
              <%= form.text_field :name, :class => 'form-control'%>
            </div>

            <div class="field">
              <%= form.label :office %>
              <%= form.text_field :office, :class => 'form-control'%>
            </div>

            <div class="field">
              <%= form.label :site %>
              <%= form.text_field :site, :class => 'form-control'%>
            </div>

            <div class="field">
              <%= form.label :latitude %>
              <%= form.text_field :latitude, :class => 'form-control'%>
            </div>

            <div class="field">
              <%= form.label :longitude %>
              <%= form.text_field :longitude, :class => 'form-control'%>
            </div>

            <div class="actions">
              <%= form.submit :class => 'btn btn-secondary'  %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/services/edit.html.erb
<% if current_user %> 
<%= render 'form', service: @service %>

<%= link_to '<button class="btn btn-success" type="button"><i class="fas fa-book-open"></i> Show</button>'.html_safe, @service %>
<%= link_to '<button class="btn btn-primary" type="button"><i class="fa fa-arrow-left"></i> Back</button>'.html_safe, services_path %>
<%else%>
  <div class="jumbotron">
  <div class="container">
    <h1>Access negate!</h1>
  </div>
  </div>
<%end%>

app/views/services/index.html.erb
<% if current_user %> 
  <div class="row">
    <div class="col-sm-12">
      <div class="card bg-dark">
        <div class="text-center text-white card-header bg-dark">
          <h1><i class="fas fa-cogs"></i> Manage services</h1>
        </div>
      </div>
      <hr>
      <div class="scroll-tab scroll-x-tab">
        <p id="notice"><%= notice %></p>
        <div class="table-responsive">
          <table class="table table-striped table-dark">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Office</th>
                <th scope="col">Site</th>
                <th scope="col">Latitude</th>
                <th scope="col">Longitude</th>
                <th scope="col">Action</th>
              </tr>
            </thead>

            <tbody>
              <% @services.each do |service| %>
                <tr scope="row">
                  <td><%= service.name %></td>
                  <td><%= service.office %></td>
                  <td><%= service.site %></td>
                  <td><%= service.latitude %></td>
                  <td><%= service.longitude %></td>
                  <td>
                    <div class="dropdown">
                      <button class="btn btn-secondary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Select
                      </button>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <%= link_to '<button class="dropdown-item btn btn-light" type="button">Show</button>'.html_safe, service %>
                        <%= link_to '<button class="dropdown-item btn btn-light" type="button">Edit</button>'.html_safe, edit_service_path(service) %>
                        <%= link_to '<button class="dropdown-item btn btn-light" type="button">Destroy</button>'.html_safe, service, method: :delete, data: { confirm: 'Are you sure?' } %>
                      </div>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <br/>
  <%= link_to '<button class="btn btn-success" type="button"><i class="fas fa-plus"></i> New Service</button>'.html_safe, new_service_path %>
  <%= link_to '<button class="btn btn-primary" type="button"><i class="fa fa-arrow-left"></i> Back</button>'.html_safe, pages_path %>
  <br/>
  &nbsp
<% else %>
  <p id="notice"><%= notice %></p>
  <div class="card">
    <div class="text-center card-header">
      <h2><i class="far fa-gem"></i> Services</h2>
    </div>
  </div>
  <hr>
  <service-list></service-list>
  <googlemap></googlemap>
<% end %>

app/views/services/new.html.erb
<% if current_user %> 
<%= render 'form', service: @service %>

<%= link_to '<button class="btn btn-primary" type="button"><i class="fa fa-arrow-left"></i> Back</button>'.html_safe, services_path %>
<br/>
&nbsp
<%else%>
  <div class="jumbotron">
  <div class="container">
    <h1>Access negate!</h1>
  </div>
  </div>
<%end%>

app/views/services/show.html.erb
<% if current_user %> 
<div class="card scroll">
  <div class="card-header">
    <div class="text-center">
      <h3><i class="fas fa-book"></i> <%= @service.name %></h3>
    </div>
  </div>
  <div class="card-body text-white bg-dark">
  <p id="notice"><%= notice %></p>
    <p>
      <strong>Name:</strong>
      <%= @service.name %>
    </p>

    <p>
      <strong>Office:</strong>
      <%= @service.office %>
    </p>

    <p>
      <strong>Site:</strong>
      <%= @service.site %>
    </p>

    <p>
      <strong>Latitude:</strong>
      <%= @service.latitude %>
    </p>

    <p>
      <strong>Longitude:</strong>
      <%= @service.longitude %>
    </p>
  </div>
</div>
<%= link_to '<button class="btn btn-success" type="button"><i class="fas fa-pencil-alt"></i> Edit</button>'.html_safe, edit_service_path(@service) %>
<%= link_to '<button class="btn btn-primary" type="button"><i class="fa fa-arrow-left"></i> Back</button>'.html_safe, services_path %>
<br/>
<%else%>
  <div class="jumbotron">
  <div class="container">
    <h1>Access negate!</h1>
  </div>
  </div>
<%end%>