config/routes.rb
Rails.application.routes.draw do
  #resources :represents
  resources :departments
  resources :courses
  resources :tutorials
  resources :tags
  resources :services#, except: :create #per evitare che mi risponda create al posto di find_near_services con metodo POST
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :user_sessions, only: [:create, :destroy]
  resources :users, only: [:index, :new, :create]
  resources :pages, only: [:index]
  #root to: 'tags#index'
  get '/', to: 'tags#index'
  get 'tags', to: 'tags#index'
  get 'tutorials', to:'tutorials#index'
  get 'services', to:'services#index'
  get 'result', to: 'tags#index'
  post 'result', to: 'courses#result'
  post 'servicesa.json', to: 'services#find_near_services'
  get 'departments.json', to: 'departments#index'
  delete 'sign_out', to: 'user_sessions#destroy', as: :sign_out
  get 'sign_in', to: 'user_sessions#new', as: :sign_in
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
    has_many :maps
    has_many :tags, through: :maps

    #ordino i tutorial in ordine alfabetico in base al titolo
    def self.order_tutorial
        tutorials = Tutorial.order(title: :asc)
    end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :set_tutorial, only: [:show, :edit, :update, :destroy]

  # GET /tutorials
  # GET /tutorials.json
  def index
    @tutorials = Tutorial.order_tutorial
    respond_to do |format|
      format.html
      format.json { render json: @tutorials }
    end
  end

  # GET /tutorials/1
  # GET /tutorials/1.json
  def show
  end

  # GET /tutorials/new
  def new
    @tutorial = Tutorial.new
  end

  # GET /tutorials/1/edit
  def edit
  end

  # POST /tutorials
  # POST /tutorials.json
  def create
    @tutorial = Tutorial.new(tutorial_params)

    respond_to do |format|
      if @tutorial.save
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully created.' }
        format.json { render :show, status: :created, location: @tutorial }
      else
        format.html { render :new }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutorials/1
  # PATCH/PUT /tutorials/1.json
  def update
    respond_to do |format|
      if @tutorial.update(tutorial_params)
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutorial }
      else
        format.html { render :edit }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutorials/1
  # DELETE /tutorials/1.json
  def destroy
    @tutorial.destroy
    respond_to do |format|
      format.html { redirect_to tutorials_url, notice: 'Tutorial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutorial
      @tutorial = Tutorial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutorial_params
      params.require(:tutorial).permit(:title, :description)
    end
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/tutorials/_form.html.erb
<%= form_with(model: tutorial, local: true) do |form| %>
  <% if tutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tutorial.errors.count, "error") %> prohibited this tutorial from being saved:</h2>

      <ul>
      <% tutorial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <div class="text-center">
            <h3><i class="fas fa-pencil-alt"></i> <%=@tutorial.title%></h3>
          </div>
        </div>

        <div class="card-body text-white bg-dark scroll scroll-x">
          <div class="form-group">

            <div class="field">
              <%= form.label :title %>
              <%= form.text_field :title, :class => 'form-control' %>
            </div>

            <div class="field">
              <%= form.label :description %>
              <%= form.text_field :description, :class => 'form-control' %>
            </div>

            <div class="field">
              <%= form.label :site %>
              <%= form.text_field :site, :class => 'form-control' %>
            </div>
            <div class="actions">
              <%= form.submit :class => 'btn btn-secondary'  %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/tutorials/edit.html.erb
<% if current_user %> 
<%= render 'form', tutorial: @tutorial %>

<%= link_to '<button class="btn btn-success" type="button"><i class="fas fa-book-open"></i> Show</button>'.html_safe, @tutorial %>
<%= link_to '<button class="btn btn-primary" type="button"><i class="fa fa-arrow-left"></i> Back</button>'.html_safe, tutorials_path %>

<br/>
&nbsp
<% else %>
  <div class="jumbotron">
  <div class="container">
    <h1>Access negate!</h1>
  </div>
  </div>
<% end %>

app/views/tutorials/index.html.erb
<% if current_user %> 
  <div class="row">
    <div class="col-sm-12">
    <div class="card bg-dark">
      <div class="text-center text-white card-header bg-dark">
        <h1><i class="fas fa-cogs"></i> Manage tutorials</h1>
      </div>
    </div>
      <hr>
      <div class="scroll-tab scroll-x-tab">
        <p id="notice"><%= notice %></p>
        <div class="table-responsive">
          <table class="table table-striped table-dark">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Site</th>
                <th scope="col">Action</th>
              </tr>
            </thead>

            <tbody>
              <% @tutorials.each do |tutorial| %>
                <tr scope="row">
                  <td><%= tutorial.title %></td>
                  <td><div class="scroll-td"><%= tutorial.description %></div></td>
                  <td><div class="scroll-x-td"><%= tutorial.site %></div></td>
                  <td>
                    <div class="dropdown"></div>
                      <button class="btn btn-secondary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Select
                      </button>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <%= link_to '<button class="dropdown-item btn btn-light" type="button">Show</button>'.html_safe, tutorial %>
                        <%= link_to '<button class="dropdown-item btn btn-light" type="button">Edit</button>'.html_safe, edit_tutorial_path(tutorial) %>
                        <%= link_to '<button class="dropdown-item btn btn-light" type="button">Destroy</button>'.html_safe, tutorial, method: :delete, data: { confirm: 'Are you sure?' } %>
                      </div>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <br/>
  <%= link_to '<button class="btn btn-success" type="button"><i class="fas fa-plus"></i> New Tutorial</button>'.html_safe, new_tutorial_path %>
  <%= link_to '<button class="btn btn-primary" type="button"><i class="fa fa-arrow-left"></i> Back</button>'.html_safe, pages_path %>
  <br/>
  &nbsp
<% else %>
  <p id="notice"><%= notice %></p>
  <div class="card">
    <div class="text-center card-header">
    <h2><i class="fas fa-book-open"></i> Tutorials</h2>
    </div>
  </div>
    <hr>
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-lg-4">
                <tutorial-list></tutorial-list>
            </div>
            <div class="col-sm-6 col-lg-8">
                <tutorial-description></tutorial-description>
            </div>
            <div class="col-sm-12 col-lg-12">
              <div class="card text-center">
              <h5> Issues? Send us a message! <a href="https://www.facebook.com/INGUNIFE/"><i class="fab fa-facebook-square"></i></a></h5>
              </div>
            </div>
        </div>
    </div>
<% end %>

app/views/tutorials/new.html.erb
<% if current_user %> 
<%= render 'form', tutorial: @tutorial %>

<%= link_to '<button class="btn btn-primary" type="button"><i class="fa fa-arrow-left"></i> Back</button>'.html_safe, tutorials_path %>
<br/>
&nbsp
<% else %>
  <div class="jumbotron">
  <div class="container">
    <h1>Access negate!</h1>
  </div>
  </div>
<% end %>

app/views/tutorials/show.html.erb
<% if current_user %> 
<div class="card scroll">
  <div class="card-header">
    <div class="text-center">
      <h3><i class="fas fa-book"></i>  <%= @tutorial.title %></h3>
    </div>
  </div>
  <div class="card-body text-white bg-dark">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Title:</strong>
      <%= @tutorial.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @tutorial.description %>
    </p>
  </div>
</div>
<%= link_to '<button class="btn btn-success" type="button"><i class="fas fa-pencil-alt"></i> Edit</button>'.html_safe, edit_tutorial_path(@tutorial) %>
<%= link_to '<button class="btn btn-primary" type="button"><i class="fa fa-arrow-left"></i> Back</button>'.html_safe, tutorials_path %>
<br/>
&nbsp
<% else %>
  <div class="jumbotron">
  <div class="container">
    <h1>Access negate!</h1>
  </div>
  </div>
<% end %>