config/routes.rb
Rails.application.routes.draw do
  #resources :represents
  resources :departments
  resources :courses
  resources :tutorials
  resources :tags
  resources :services#, except: :create #per evitare che mi risponda create al posto di find_near_services con metodo POST
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :user_sessions, only: [:create, :destroy]
  resources :users, only: [:index, :new, :create]
  resources :pages, only: [:index]
  #root to: 'tags#index'
  get '/', to: 'tags#index'
  get 'tags', to: 'tags#index'
  get 'tutorials', to:'tutorials#index'
  get 'services', to:'services#index'
  get 'result', to: 'tags#index'
  post 'result', to: 'courses#result'
  post 'servicesa.json', to: 'services#find_near_services'
  get 'departments.json', to: 'departments#index'
  delete 'sign_out', to: 'user_sessions#destroy', as: :sign_out
  get 'sign_in', to: 'user_sessions#new', as: :sign_in
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :represent
    has_many :courses, through: :represent
    has_many :connects
    has_many :services, through: :connects
    has_many :maps
    has_many :tutorials, through: :maps
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
     respond_to do |format|
      format.html
      format.json { render json: @tags }
     end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :tag_type)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <div class="text-center">
            <h3><i class="fas fa-pencil-alt"></i> #<%=@tag.name%></h3>
          </div>
        </div>

        <div class="card-body text-white bg-dark scroll scroll-x">
          <div class="form-group">
             <div class="field">
              <%= form.label :name %>
              <%= form.text_field :name, :class => 'form-control' %>
            </div>

            <div class="field">
              <%= form.label :tag_type %>
              <%= form.text_field :tag_type, :class => 'form-control' %>
            </div>
            <br/>
            <div class="actions">
              <%= form.submit :class => 'btn btn-secondary'  %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/tags/edit.html.erb
<% if current_user%>
<%= render 'form', tag: @tag %>

<%= link_to '<button class="btn btn-success" type="button"><i class="fas fa-book-open"></i> Show</button>'.html_safe, @tag %>
<%= link_to '<button class="btn btn-primary" type="button"><i class="fa fa-arrow-left"></i> Back</button>'.html_safe, tags_path %>

<br/>
&nbsp
<% else %>
  <div class="jumbotron">
  <div class="container">
    <h1>Access negate!</h1>
  </div>
  </div>
<% end %>

app/views/tags/index.html.erb
<% if current_user%>
    <div class="row">
    <div class="col-sm-12">
      <div class="card bg-dark">
        <div class="text-center text-white card-header bg-dark">
          <h1><i class="fas fa-cogs"></i> Manage tags</h1>
        </div>
      </div>
      <hr>
      <div class="scroll-tab scroll-x-tab">
        <p id="notice"><%= notice %></p>
        <div class="table-responsive">
          <table class="table table-striped table-dark">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Type</th>
                <th scope="col">Action</th>
              </tr>
            </thead>

            <tbody>
              <% @tags.each do |tag| %>
                <tr scope="row">
                  <td><%= tag.name %></td>
                  <td><%= tag.tag_type%>
                  <td>
                    <div class="dropdown">
                      <button class="btn btn-secondary dropdown-toggle btn-sm" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Select
                      </button>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <%= link_to '<button class="dropdown-item btn btn-light" type="button">Show</button>'.html_safe, tag %>
                        <%= link_to '<button class="dropdown-item btn btn-light" type="button">Edit</button>'.html_safe, edit_tag_path(tag) %>
                        <%= link_to '<button class="dropdown-item btn btn-light" type="button">Destroy</button>'.html_safe, tag, method: :delete, data: { confirm: 'Are you sure?' } %>
                      </div>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <br/>
  <%= link_to '<button class="btn btn-success" type="button"><i class="fas fa-plus"></i> New Tag</button>'.html_safe, new_tag_path %>
  <%= link_to '<button class="btn btn-primary" type="button"><i class="fa fa-arrow-left"></i> Back</button>'.html_safe, pages_path %>
  <br/>
  &nbsp
<%else%>
  <p id="notice"><%= notice %></p>
  <div class="card">
    <div class="text-center card-header">
      <h2><i class="far fa-lightbulb"></i> Attitudes</h2>
    </div>
  </div>
  <hr>
  <div class="row">
    <tags-list></tags-list>
    <result></result>
  </div>
<%end%>

app/views/tags/new.html.erb
<% if current_user%>
<%= render 'form', tag: @tag %>

<%= link_to '<button class="btn btn-primary" type="button"><i class="fa fa-arrow-left"></i> Back</button>'.html_safe, tags_path %>
<br/>
&nbsp
<% else %>
  <div class="jumbotron">
  <div class="container">
    <h1>Access negate!</h1>
  </div>
  </div>
<% end %>

app/views/tags/old_index.html.erb
<p id="notice"><%= notice %></p>

<div class="text-center">
  <h1>Attitudes</h1>
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= tag.type %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/show.html.erb
<% if current_user%>
<div class="card scroll">
  <div class="card-header">
    <div class="text-center">
      <h3><i class="fas fa-book"></i> <%= @tag.name %></h3>
    </div>
  </div>
  <div class="card-body text-white bg-dark">
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Name:</strong>
      <%= @tag.name %>
    </p>

    <p>
      <strong>Type:</strong>
      <%= @tag.tag_type %>
    </p>
  </div>
</div>
<%= link_to '<button class="btn btn-success" type="button"><i class="fas fa-pencil-alt"></i> Edit</button>'.html_safe, edit_tag_path(@tag) %>
<%= link_to '<button class="btn btn-primary" type="button"><i class="fa fa-arrow-left"></i> Back</button>'.html_safe, tags_path %>
<br/>
<% else %>
  <div class="jumbotron">
  <div class="container">
    <h1>Access negate!</h1>
  </div>
  </div>
<% end %>