config/routes.rb
Rails.application.routes.draw do
  #resources :represents
  resources :departments
  resources :courses
  resources :tutorials
  resources :tags
  resources :services#, except: :create #per evitare che mi risponda create al posto di find_near_services con metodo POST
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :user_sessions, only: [:create, :destroy]
  resources :users, only: [:index, :new, :create]
  resources :pages, only: [:index]
  #root to: 'tags#index'
  get '/', to: 'tags#index'
  get 'tags', to: 'tags#index'
  get 'tutorials', to:'tutorials#index'
  get 'services', to:'services#index'
  get 'result', to: 'tags#index'
  post 'result', to: 'courses#result'
  post 'servicesa.json', to: 'services#find_near_services'
  get 'departments.json', to: 'departments#index'
  delete 'sign_out', to: 'user_sessions#destroy', as: :sign_out
  get 'sign_in', to: 'user_sessions#new', as: :sign_in
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    belongs_to :department, optional: true
    has_many :represents
    has_many :tags, through: :represents

    def self.find_course(tags)
        if tags.count >= 5
            courses = Course.joins(:tags).where(:tags => { :id => [tags] })
                .having("count(tags.name) >= ?", tags.count - 2).group('courses.id')
        elsif tags.count >= 3
            courses = Course.joins(:tags).where(:tags => { :id => [tags] })
                .having("count(tags.name) >= ?", tags.count - 1).group('courses.id')
        else
            courses = Course.joins(:tags).where(:tags => { :id => [tags] })
                .having("count(tags.name) = ?", tags.count).group('courses.id')
        end
    end

    def self.random_course()
        random_course = Course.order("RANDOM()").all.limit(2)
    end
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :courses
end

app/models/represent.rb
class Represent < ApplicationRecord
    belongs_to :tag, optional: true
    belongs_to :course, optional: true
end

app/models/service.rb
class Service < ApplicationRecord
    has_many :connects
    has_many :tags, through: :connects

    def self.find_services_by_department_lat_lng(latitude, longitude)
        if(latitude[0] == '-')
            lat = latitude[0..5]
        else
            lat = latitude[0..4]
        end
        if(longitude[0] == '-')
            lng = longitude[0..5]
        else
            lng = longitude[0..4]
        end
        lat = lat + '%'
        lng = lng + '%'
        services1 = Service.where("latitude LIKE ? AND longitude LIKE ?", lat, lng)
        services = services1
        n_serv = services1.count
        if(n_serv <= 2)
            new_lng = longitude.to_f
            new_lng += 0.01
            new_lng = new_lng.to_s
            if(new_lng[0] == '-')
                n_lng = new_lng[0..5]
            else
                n_lng = new_lng[0..4]
            end
            n_lng = n_lng + '%'
            services2 = Service.where("latitude LIKE ? AND longitude LIKE ?", lat, n_lng)
            services = services1 | services2
            n_serv = services2.count
            #da deccomentare qual'ora si sia in un'altro meridiano
            # if(n_serv <= 2)
            #     new_lat = latitude.to_f
            #     new_lat += 0.01
            #     new_lat = new_lat.to_s
            #     if(new_lat[0] == '-')
            #         n_lat = new_lat[0..5]
            #     else
            #         n_lat = new_lat[0..4]
            #     end
            #     n_lat = n_lat + '%'
            #     services3 = Service.where("latitude LIKE ? AND longitude LIKE ?", n_lat, lng)
            #     services = services1 | services2 | services3
            # end
        end
        return services
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :represent
    has_many :courses, through: :represent
    has_many :connects
    has_many :services, through: :connects
    has_many :maps
    has_many :tutorials, through: :maps
end

app/models/tutorial.rb
class Tutorial < ApplicationRecord
    has_many :maps
    has_many :tags, through: :maps

    #ordino i tutorial in ordine alfabetico in base al titolo
    def self.order_tutorial
        tutorials = Tutorial.order(title: :asc)
    end
end

app/models/user.rb
class User < ApplicationRecord

    acts_as_authentic

    def deliver_password_reset_instructions!
        reset_perishable_token!
        PasswordResetMailer.reset_email(self).deliver_now
    end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
     respond_to do |format|
      format.html
      format.json { render json: @tags }
     end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :tag_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/represents_helper.rb
module RepresentsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-lg navbar-light back text-center">
  <div class="col-sm-12 col-lg-12">
    <a class="navbar-brand" href="https://www.facebook.com/unife.it/"><i class="fab fa-facebook-square"></i></a>
    <a class="navbar-brand" href="https://www.instagram.com/unife.it/?hl=it"><i class="fab fa-instagram"></i></a>
    <a class="navbar-brand" href="https://www.linkedin.com/school/università-degli-studi-di-ferrara/"><i class="fab fa-linkedin"></i></a>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light back">
  <a class="navbar-brand" href="https://www.unife.it"><img class="mx-auto d-block" src="/img/logo.png" alt="logounife" id="logoUnife"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto" id="myHeader">
      <li class="nav-item active ml-auto">
         <%= link_to raw('<h6><i class="fas fa-lightbulb"></i> Attitudes</h6>'), tags_path, class: "nav-link"  %>
      </li>
      <li class="nav-item active ml-auto">
        <%= link_to raw('<h6><i class="fas fa-gem"></i> Services </h6>'), services_path, class: "nav-link"  %>
      </li>
      <li class="nav-item active ml-auto">
        <%= link_to raw('<h6><i class="fas fa-book-open"></i> Tutorials</h6>'), tutorials_path, class: "nav-link"  %>
      </li>
      <li class="nav-item active ml-auto">
        <%= link_to raw('<h6><i class="fas fa-user-shield"></i> Admin</h6>'), pages_path, class: "nav-link"  %>
      </li>
      <% if current_user %>
        <li  class="nav-item active ml-auto">
          <%= link_to raw('<h6><i class="fas fa-sign-out-alt"></i> Logout</h4>'), sign_out_path, method: :delete, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wwwelcome</title>

    <!--script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDlwdCJJ7cmhz4KRHsRSDMKWNBnTxFpTZY" ></script-->
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js" integrity="sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>

  </head>

  <body style="background-image: url('/img/unife.JPG'); background-size:cover;">
    <div class="container" id="app">
      <%= render "layouts/header" %>
      <hr>
      <%= yield %>
    </div>
     <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>